"""empty message

Revision ID: 192340afc3d4
Revises: 
Create Date: 2019-11-09 19:18:28.227790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192340afc3d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookoutlet_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=320), nullable=False),
    sa.Column('series', sa.String(length=320), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('scratch_n_dent', sa.Boolean(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('link', sa.String(length=75), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goodreads_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=320), nullable=False),
    sa.Column('title_series', sa.String(length=320), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('img_file', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('goodreads_id', sa.String(length=75), nullable=False),
    sa.Column('request_token', sa.String(length=120), nullable=True),
    sa.Column('request_secret', sa.String(length=120), nullable=True),
    sa.Column('access_token', sa.String(length=120), nullable=True),
    sa.Column('access_secret', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('goodreads_book')
    op.drop_table('bookoutlet_book')
    # ### end Alembic commands ###
